name: resculpt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  lottie: ^1.1.0
  rive: ^0.12.3
  flutter_svg: ^2.0.9
  camera: ^0.10.5+6
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.5
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  razorpay_flutter: ^1.3.5
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/RiveAssets/

  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
